name: Deploy
on:
  push: 
    branches: [ main ]
concurrency:
  group: envirs-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_DOMAIN }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd  /home/koodaki/koodaki-customer          
            eval "$(ssh-agent -s)" ssh-add /home/koodaki/keys/customer.key
            git reset --hard
            git pull 
            npm install
            ng build --configuration=production  