name: Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]
concurrency:
  group: envirs-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_DOMAIN }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www/frontEnd/koodaki-customer
          npm install
          nvm use 16.18.1
          pm2 stop "npm run start" --name "customer"
          git pull
          npm run build:prod
          pm2 start "npm run start" --name "customer"
