name: Deploy
on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ develop ]
concurrency:
  group: envirs-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_DOMAIN }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www/frontEnd/koodaki-customer
          nvm use 16.18.1
          pm2 stop "npx ng serve --open --host 103.75.198.71 --port 3008 --disable-host-check" --name "customer"
          git pull 
          npm run build
          pm2 start "npx ng serve --open --host 103.75.198.71 --port 3008 --disable-host-check" --name "customer"
